package br.com.coretecnologia.pagamento;
// Generated 06/10/2019 11:39:00 by Hibernate Tools 5.2.12.Final

/**
 * PagamentoId generated by hbm2java
 */
public class PagamentoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long cpf;
	private long cdcurso;

	public PagamentoId() {
	}

	public PagamentoId(long cpf, long cdcurso) {
		this.cpf = cpf;
		this.cdcurso = cdcurso;
	}

	public long getCpf() {
		return this.cpf;
	}

	public void setCpf(long cpf) {
		this.cpf = cpf;
	}

	public long getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(long cdcurso) {
		this.cdcurso = cdcurso;
	}
}
