package br.com.coretecnologia.pagamento;
// Generated 06/10/2019 11:39:00 by Hibernate Tools 5.2.12.Final

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PagamentoId id;
	private String datainscricao;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id, String datainscricao) {
		this.id = id;
		this.datainscricao = datainscricao;
	}

	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	public String getDatainscricao() {
		return this.datainscricao;
	}

	public void setDatainscricao(String datainscricao) {
		this.datainscricao = datainscricao;
	}
	
	@Override
	public String toString() {
		return "Pagamento [cdcurso="+ id.getCpf() +" cdcurso="+ id.getCdcurso() +" data_inscricao="+ datainscricao +"]";
	}
}
